### PR TITLE
OpenNi driver speedup + bugfixes (+ merge with upstream)

### PR DESCRIPTION
**Pull request by HenningJ**
As discussed in issue libfreenect2/#243 I did the following:
- Instead of directly processing the frames in the onNewFrame() callback, I'm using the `SyncMultiFrameListener` like in protonect
- the OpenNI frames are created in a separate thread
- the `libreenect2::Registration` is applied to the whole image instead of each pixel individually

Since the last change requires a more current version of libfreenect2 than you have, I just merged in the current master. I hope thats ok.

I also fixed a bug that caused a crash when closing the device.

### CODE REVIEW

**Comment by HenningJ** [comment]
I just noticed something: If libfreenect2 doesn't send new frames, this implementation will forever hand at [`listener.waitForNewFrame(frames);`](https://github.com/hanyazou/libfreenect2/pull/1/files#diff-fbc85e14c9b96ea6723a85cc7ac90370R69). That shouldn't be a problem, since it's a separate thread that doesn't do anything but provide new frames to OpenNI. But OpenNi (or at least the NiViewer) doesn't seem to handle that well.

If you got the `std::thread` implementation instead of the `tinythread` one, you should probably change that line to the `waitForNewFrame()` method with a timeout.

**Comment by hanyazou** [comment]
@HenningJ Thank you for your feedback. But please take a breather. I will merge from upstream this weekend and fix my issues. I will also cherry-pick your bug fix of closing device to check stability. Please send your modification then. Sorry for inconvenient and I hope this works for you.

**Comment by HenningJ** [comment]
Sure, no problem. Just say when your ready :-)

**Comment by hanyazou** [comment]
I've merged from upstream and HenningJ's patches. Thanks a lot.

**Pull request closed without merging**
